# Generated by Django 2.2.3 on 2019-07-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_post_like_post_like_count_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_like',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.userinfo'),
        ),
        migrations.AlterField(
            model_name='post_like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.post'),
        ),
    ]
